# Generated by Django 5.2.6 on 2026-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('feature', 'Yangi funksiya'), ('improvement', 'Yaxshilash'), ('announcement', "E'lon"), ('bugfix', 'Xato tuzatish')], default='announcement', max_length=30, verbose_name='Yangilik turi')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
