# Generated by Django 5.2.6 on 2026-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('old', 'Eski')], default='new', max_length=20, verbose_name='Holati'),
        ),
        migrations.DeleteModel(
            name='NewsUnread',
        ),
    ]
