# Generated by Django 5.2.6 on 2026-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options_rename_content_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Yangi'), ('old', 'Eski')], default='new', max_length=20, null=True, verbose_name='Holati'),
        ),
    ]
