# Generated by Django 5.2.6 on 2026-01-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('old', 'Eski')], default='new', max_length=20, verbose_name='Holati'),
        ),
    ]
