# Generated by Django 5.2.6 on 2026-01-28 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Sertifikat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sertifikat tavsifi')),
                ('issued_date', models.DateField(verbose_name='Berilgan sana')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Sertifikat egasi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_date'],
            },
        ),
    ]
