# Generated by Django 5.2.8 on 2025-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='smena',
            field=models.CharField(max_length=500, verbose_name='Guruh Smenasi'),
        ),
    ]
