# Generated by Django 5.2.8 on 2025-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='class_days',
            field=models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba'), ('sunday', 'Yakshanba')], default=1, max_length=50, verbose_name='Dars kunlari'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.DateTimeField(verbose_name='Boshlanish vaqti'),
        ),
    ]
