# Generated by Django 5.2.8 on 2025-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_class_days_alter_group_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
