# Generated by Django 5.2.8 on 2025-12-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.CharField(max_length=500, verbose_name='Guruh Smenasi'),
        ),
    ]
