# Generated by Django 5.2.8 on 2025-12-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_students'),
        ('groups', '0004_group_students_alter_group_smena_and_more'),
    ]

    operations = [
    ]
