# Generated by Django 5.2.8 on 2025-12-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_merge_20251201_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
    ]
