# Generated by Django 5.2.6 on 2025-11-16 02:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='QR UUID')),
                ('image_qrkod', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code image')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Phone number')),
                ('tg_username', models.CharField(blank=True, max_length=150, verbose_name='Telegram username')),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50, verbose_name='Level')),
                ('course', models.CharField(blank=True, choices=[('kurs-1', '1-kurs'), ('kurs-2', '2-kurs'), ('kurs-3', '3-kurs'), ('kurs-4', '4-kurs'), ('kurs-5', '5-kurs')], max_length=50, verbose_name='Course')),
                ('direction', models.CharField(blank=True, max_length=255, verbose_name='Direction')),
                ('coins', models.IntegerField(default=0, verbose_name='Coins')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Photo')),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=50, verbose_name='Foydalanuvchi roli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol foydalanuvchi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
