# Generated by Django 5.2.6 on 2025-11-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='QR UUID'),
        ),
    ]
