# Generated by Django 5.2.6 on 2025-11-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Foydalanuvchi rasmi'),
        ),
    ]
