# Generated by Django 5.2.6 on 2025-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', "O'qituvchi"), ('admin', 'Admin')], default='student', max_length=50, verbose_name='Foydalanuvchi roli'),
        ),
    ]
