# Generated by Django 5.2.6 on 2026-01-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_qrkod',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invite code (PROMOKOD)'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone_number',
            field=models.JSONField(blank=True, null=True, verbose_name='Parent phone numbers'),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('friend', "Do'st"), ('other', 'Boshqa')], max_length=255, null=True, verbose_name='Social source'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Ball (0/100)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram username'),
        ),
    ]
