# Generated by Django 5.2.6 on 2026-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_direction_remove_user_image_qrkod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ball (0/100)'),
        ),
    ]
