# Generated by Django 5.2.6 on 2026-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ball (0/100)'),
        ),
    ]
