# Generated by Django 5.2.6 on 2026-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='group',
        ),
    ]
