# Generated by Django 5.2.6 on 2026-01-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_course_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.JSONField(blank=True, null=True, verbose_name='Group'),
        ),
    ]
