# Generated by Django 5.2.6 on 2026-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group ID'),
        ),
    ]
