# Generated by Django 5.2.6 on 2026-01-30 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_group_delete_group'),
        ('groups', '0004_alter_group_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Reason (Sababli bo'lsa)"),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('excuse', 'Sababli')], max_length=20, null=True, verbose_name='Attendance Status'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('group', 'user', 'date')},
        ),
    ]
