# Generated by Django 5.2.6 on 2026-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Ball (o'sha kun uchun)"),
        ),
    ]
