# Generated by Django 5.2.6 on 2025-11-24 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='MessagesModel',
        ),
        migrations.AlterModelOptions(
            name='messagesmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sms yuborish', 'verbose_name_plural': 'Smslar'},
        ),
    ]
