# Generated by Django 5.2.6 on 2025-11-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_admin_i_5a5069_idx',
            old_name='messages_me_admin_i_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_student_6a634f_idx',
            old_name='messages_me_student_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__b02346_idx',
            old_name='messages_me_sender_idx',
        ),
    ]
