# Generated by Django 5.2.6 on 2025-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_messages_me_admin_i_idx_chat_messag_admin_i_5a5069_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilganmi?"),
        ),
    ]
